server:
  port: 8080

spring:
  application:
    name: course-management-system
  
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

# JWT Configuration
jwt:
  secret: your-secret-key-here-make-it-very-long-and-secure-in-production
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins:
   http://localhost:3000
   https://course-management-system-frontend-qop9.onrender.com

  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
